__all__ = ['MIN_FIRST_NAME_LENGTH', 'MAX_FIRST_NAME_LENGTH', 'MIN_LAST_NAME_LENGTH', 'MAX_LAST_NAME_LENGTH',
           'MIN_USERNAME_LENGTH', 'MAX_USERNAME_LENGTH', 'MIN_PASSWORD_LENGTH', 'MAX_PASSWORD_LENGTH']


MIN_FIRST_NAME_LENGTH = 5
MAX_FIRST_NAME_LENGTH = 30

MIN_LAST_NAME_LENGTH = 5
MAX_LAST_NAME_LENGTH = 30

MIN_USERNAME_LENGTH = 5
MAX_USERNAME_LENGTH = 30


MIN_PASSWORD_LENGTH = 5
MAX_PASSWORD_LENGTH = 10
