from socialmedia.constants.numeric.user import MIN_FIRST_NAME_LENGTH, MAX_FIRST_NAME_LENGTH, \
    MIN_LAST_NAME_LENGTH, MAX_LAST_NAME_LENGTH, \
    MIN_USERNAME_LENGTH, MAX_USERNAME_LENGTH, \
    MIN_PASSWORD_LENGTH, MAX_PASSWORD_LENGTH


__all__ = ['FIRST_NAME_EMPTY_ERROR_STRING', 'MIN_FIRST_NAME_ERROR_STRING', 'MAX_FIRST_NAME_ERROR_STRING',
           'LAST_NAME_EMPTY_ERROR_STRING', 'MIN_LAST_NAME_ERROR_STRING', 'MAX_LAST_NAME_ERROR_STRING',
           'USERNAME_EMPTY_ERROR_STRING', 'MIN_USERNAME_ERROR_STRING', 'MAX_USERNAME_ERROR_STRING',
           'EMAIL_EMPTY_ERROR_STRING', 'EMAIL_INVALID_ERROR_STRING',
           'PASSWORD_EMPTY_ERROR_STRING', 'MIN_PASSWORD_ERROR_STRING',
           'MAX_PASSWORD_ERROR_STRING', 'USER_NOT_FOUND_ERROR_STRING', 'USER_NOT_VALID_ERROR_STRING',
           'USER_ALREADY_EXISTS_ERROR_STRING', 'USER_UNAUTHENTICATED_ERROR_STRING',
           'USER_REQUESTING_INVALID_USER_ID_ERROR_STRING', 'USER_REQUESTING_ANOTHER_USER_ID_ERROR_STRING']

FIRST_NAME_EMPTY_ERROR_STRING = 'First name is a mandatory field'
MIN_FIRST_NAME_ERROR_STRING = f'First name must have at least {MIN_FIRST_NAME_LENGTH} characters'
MAX_FIRST_NAME_ERROR_STRING = f'First name can\'t have more than {MAX_FIRST_NAME_LENGTH} characters'

LAST_NAME_EMPTY_ERROR_STRING = 'Last name is a mandatory field'
MIN_LAST_NAME_ERROR_STRING = f'Last name must have at least {MIN_LAST_NAME_LENGTH} characters'
MAX_LAST_NAME_ERROR_STRING = f'Last name can\'t have more than {MAX_LAST_NAME_LENGTH} characters'

USERNAME_EMPTY_ERROR_STRING = 'Username is a mandatory field'
MIN_USERNAME_ERROR_STRING = f'Username must have at least {MIN_USERNAME_LENGTH} characters'
MAX_USERNAME_ERROR_STRING = f'Username must have at least {MAX_USERNAME_LENGTH} characters'

EMAIL_EMPTY_ERROR_STRING = 'Email is a mandatory field'
EMAIL_INVALID_ERROR_STRING = 'String is not a email'

PASSWORD_EMPTY_ERROR_STRING = 'Password is a mandatory field'
MIN_PASSWORD_ERROR_STRING = f'Password must have at least {MIN_PASSWORD_LENGTH} characters'
MAX_PASSWORD_ERROR_STRING = f'Password must have at least {MAX_PASSWORD_LENGTH} characters'


USER_NOT_FOUND_ERROR_STRING = 'Cannot find user'
USER_NOT_VALID_ERROR_STRING = 'User data is invalid'
USER_ALREADY_EXISTS_ERROR_STRING = 'User already exists'
USER_UNAUTHENTICATED_ERROR_STRING = 'User\'s password is not valid'

USER_REQUESTING_INVALID_USER_ID_ERROR_STRING = 'Id which user is requesting is invalid'
USER_REQUESTING_ANOTHER_USER_ID_ERROR_STRING = 'Cannot perform this operation on another user'
