"""user_tokens

Revision ID: 4628af0aab8c
Revises: e84188f29f66
Create Date: 2022-11-10 23:37:28.751135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4628af0aab8c'
down_revision = 'e84188f29f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token_jti', sa.String(), nullable=True),
    sa.Column('refresh_token_jti', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'refresh_token_jti')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token_jti', sa.VARCHAR(), nullable=True))
    op.drop_table('user_tokens')
    # ### end Alembic commands ###
