"""datetime

Revision ID: 4fbd40052c37
Revises: b30f0a572dbe
Create Date: 2023-01-28 02:56:08.062508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbd40052c37'
down_revision = 'b30f0a572dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('registered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered_at')
    op.drop_column('comment', 'created_at')
    # ### end Alembic commands ###
